### ISSUE TITLE
kubernetes integrated

### ISSUE THREAD

**Issue by chennqqi** [smallnest/rpcx#335]
Advice to add k8s deployment yaml

**Comment by botemple** [comment]
Please, also include ETCd integrated at the same time will be perfect

**Comment by smallnest** [comment]
rpcx already supports etcd/zookeeper/consul @botemple

**Comment by botemple** [comment]
I meant support rpcx & etcd in  k8s deployment  as yaml

We already add etcd (standalone) as registry ,  works great!

**Comment by smallnest** [comment]
如果你使用k8s + rpcx,和其它的应用一样，你不需要注册中心了。

对于rpcx服务来说，你使用k8s `deployment`发布一个服务即可，然后客户端直接访问它的暴露的集群的地址和端口。

例如：

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpcx-server-demo-deployment
  labels:
    app: rpcx-server-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rpcx-server-demo
  template:
    metadata:
      labels:
        app: rpcx-server-demo
    spec:
      containers:
      - name: rpcx-server-demo
        image: smallnest/rpcx-server-demo:1.0
        ports:
        - containerPort: 8972
```

最好不要和注册中心(zookeeper/etcd/consul)部署在一起。因为：
- 如果你使用k8s的负载均衡，你就不需要注册中心了
- 如果你想使用独立的注册中心，那么应该是各种服务共享注册中心，所以注册中心独立部署成服务
