### ISSUE TITLE
Travis-ci build error , EtcdV3RegisterPlugin undefined 

### ISSUE THREAD

**Issue by LockGit** [smallnest/rpcx#379]
It's my .travis.yml file 
```
language:
  go

go:
  - "1.12"
#  - master

env:
  global:
    GO111MODULE: "on"


script:
  - go install -tags "etcd" github.com/smallnest/rpcx/...
  - go get -u -v -t ./...

```

when use travis-ci build my application ,I find some error in travis-ci job log 
```
logic/publish.go:71:8: undefined: serverplugin.EtcdV3RegisterPlugin
The command "eval go get -v -t ./... " failed. Retrying, 3 of 3.
```

so when use travis-ci build application ,the -tags "etcd" should add there? or must set GO111MODULE = "off" ?

Suggest next version rpcx remove -tags option,  may have fewer lot's of unnecessary problems.
