### ISSUE TITLE
请教一个docker-compose部署多个server和一个client服务的连接报错问题。

### ISSUE THREAD

**Issue by theoneLee** [smallnest/rpcx#462]
自己写了个demo，不使用docker部署的话，单纯运行backend和service（即客户端，服务端）是可以跑通的。但是尝试用docker-compose运行1个backend和2个service时有一个问题。

架构思路的话：
- backend集成了rpcx client和gin，gin暴露http api给外部使用，rpcx client使用etcd获取service的rpc接口地址，然后调用rpc。
- service运行rpcx server，暴露rpc接口给backend使用。注册中心的话使用etcd，通过flag传入该server的地址然后注册到etcd上。

这个是backend的报错：
``` bash
[GIN-debug] Listening and serving HTTP on :3010
2020/05/29 06:26:33 connection.go:96: WARN : failed to dial server: dial tcp 10.0.0.201:8973: connect: connection refused
2020/05/29 06:26:33 connection.go:96: WARN : failed to dial server: dial tcp 10.0.0.201:8973: connect: connection refused
2020/05/29 06:26:33 connection.go:96: WARN : failed to dial server: dial tcp 10.0.0.201:8972: connect: connection refused
2020/05/29 06:26:33 connection.go:96: WARN : failed to dial server: dial tcp 10.0.0.201:8972: connect: connection refused
2020/05/29 06:26:33 connection.go:96: WARN : failed to dial server: dial tcp 10.0.0.201:8972: connect: connection refused
[GIN] 2020/05/29 - 06:26:33 | 500 |     33.5876ms |     192.168.0.1 | GET      "/api/v1/match?page=1&size=10&key=format.keyword&val=doc&index=testtable1"

```

这个是启动服务的docker-compose.yml
```yaml
version: '2'
services:
  server1:
    image: yz_classic_server:1.0
    container_name: yz_classic_server1
    entrypoint: /rpcx-service/server -addr='10.0.0.201:8972'
    ports:
      - "8972:8972"
  server2:
    image: yz_classic_server:1.0
    container_name: yz_classic_server2
    # -flag 传入addr 10.0.0.201:8973
    entrypoint: /rpcx-service/server -addr='10.0.0.201:8973'
    ports:
      - "8973:8972"
  backend:
    image: yz_classic_backend:1.0
    container_name: yz_classic_backend
    ports:
      - "3010:3010"
```

这个是backend的main.go
```go

var (
	defaultAddr = ":3010"
	addr  = flag.String("addr", defaultAddr, "http address")

	//etcd
	basePath = flag.String("base", "/rpcx_yz_classic", "prefix path")
	etcdAddr = flag.String("etcdAddr", "10.0.0.201:2379", "etcd address")
)



func main() {
	// gin + rpcx client
	dEtcd := client.NewEtcdV3Discovery(*basePath, "search", []string{*etcdAddr}, nil)
	v1.Xclient = client.NewXClient("search", client.Failover, client.RandomSelect, dEtcd, client.DefaultOption)
	defer v1.Xclient.Close()

	r := v1.InitRouter()
	r.Run(defaultAddr) // listen and serve on 0.0.0.0:3010
}

```

这个是service的main.go
```go
var (
	addr = flag.String("addr", "localhost:8972", "server address")

	//etcd
	basePath = flag.String("base", "/rpcx_yz_classic", "prefix path")
	etcdAddr = flag.String("etcdAddr", "10.0.0.201:2379", "etcd address")
)

func main() {
	flag.Parse()
	// init es dao
	dao.InitEs()

	// rpcx service
	s := server.NewServer()

	addRegistryPlugin(s) //etcd

	s.RegisterName("search", search.New(), "") //user.New()返回一个服务对象，该服务对象的所有方法都会是允许rpc调用的，只要符合方法签名
	//err := s.Serve("tcp", *addr)
	err := s.Serve("tcp", "localhost:8972")
	if err != nil {
		panic(err)
	}
}


func addRegistryPlugin(s *server.Server) {
	fmt.Println("*addr:", *addr)
	r := &serverplugin.EtcdV3RegisterPlugin{
		ServiceAddress: "tcp@" + *addr,
		EtcdServers:    []string{*etcdAddr},
		BasePath:       *basePath,
		UpdateInterval: time.Minute,
	}
	err := r.Start()
	if err != nil {
		log.Fatal(err)
	}
	s.Plugins.Add(r)
}
```
注意的是，
10.0.0.201是一台机子，里面部署了etcd；
localhost(内网ip为10.0.0.222)是另一台机子，这台机子运行了`docker-compose up -d`

自己排查了很久，但是还是不知道问题具体在哪。求指教。thx.
