### ISSUE TITLE
server etcd discover fail

### ISSUE THREAD

**Issue by baekhyunee7** [smallnest/rpcx#804]
server code:
```
func addRegistryPlugin(s *server.Server, serviceConfig *core.ServiceConfig) {
	r := &serverplugin.EtcdV3RegisterPlugin{
		ServiceAddress: "tcp@" + serviceConfig.Host,
		EtcdServers:    serviceConfig.Etcd,
		BasePath:       core.LOGIN_PREFIX,
		// Metrics:        metrics.NewRegistry(),
		UpdateInterval: time.Minute,
	}
	err := r.Start()
	if err != nil {
		logrus.Error(err)
	}
	s.Plugins.Add(r)
}
```
error: "etcdv3.go:59: ERROR: cannot create etcd registry: Backend storage not supported yet, please choose one of"

etcd docker-compose:
```
services:
  etcd:
    image: quay.io/coreos/etcd
    container_name: etcd_single
    command: etcd -name etcd1 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - /mnt/etcd/etcd:/etcd-data 
```
